/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Vertice;
import static Interfaces.CargarArchivo.grafo;
import javax.swing.DefaultComboBoxModel;

public class AgregarSeguidor extends javax.swing.JFrame {

    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    DefaultComboBoxModel modeloCombo2 = new DefaultComboBoxModel();

    public AgregarSeguidor() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.ActualizarComboBox();
        
        principal.addActionListener(e -> actualizarComboASeguir());
    }

    private void ActualizarComboBox() {
        modeloCombo.removeAllElements();
        modeloCombo2.removeAllElements();
        if (!grafo.isEmpty()) {
            for (int i = 0; i < grafo.getUsuarios().getSize(); i++) {
                Vertice verticeActual = (Vertice) grafo.getUsuarios().getValor(i);
                modeloCombo.addElement(verticeActual.getNombre());
            }

            if (modeloCombo.getSize() > 0) {
                principal.setSelectedIndex(0);
                actualizarComboASeguir();
            }
        }
    }

    private void actualizarComboASeguir() {
        modeloCombo2.removeAllElements();

        if (grafo == null || grafo.isEmpty()) {
            return;
        }

        // Usuario seleccionado en el combo principal
        String usuarioPrincipal = (String) principal.getSelectedItem();

        for (int i = 0; i < grafo.getUsuarios().getSize(); i++) {
            Vertice verticeActual = (Vertice) grafo.getUsuarios().getValor(i);
            String nombre = verticeActual.getNombre();

            // 🔹 No agregamos el usuario principal en el combo de "aSeguir"
            if (!nombre.equals(usuarioPrincipal)) {
                modeloCombo2.addElement(nombre);
            }
        }

        if (modeloCombo2.getSize() > 0) {
            aSeguir.setSelectedIndex(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        principal = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        aSeguir = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        seguir = new javax.swing.JButton();
        atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Agregar Seguidor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        principal.setModel(modeloCombo);
        principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalActionPerformed(evt);
            }
        });
        jPanel1.add(principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, -1));

        jLabel2.setText("Cuenta Principal");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 60, 90, -1));

        aSeguir.setModel(modeloCombo2);
        jPanel1.add(aSeguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 180, -1));

        jLabel3.setText("Cuenta a Seguir");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        seguir.setText("Seguir");
        seguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguirActionPerformed(evt);
            }
        });
        jPanel1.add(seguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, 370, -1));

        atras.setText("X");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void seguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguirActionPerformed
        String nombreUsuario1 = (String) principal.getSelectedItem();
        String nombreUsuario2 = (String) aSeguir.getSelectedItem();
        grafo.seguirUsuario(nombreUsuario1, nombreUsuario2);
        this.ActualizarComboBox();
    }//GEN-LAST:event_seguirActionPerformed

    private void principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_principalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarSeguidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarSeguidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarSeguidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarSeguidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarSeguidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aSeguir;
    private javax.swing.JButton atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> principal;
    private javax.swing.JButton seguir;
    // End of variables declaration//GEN-END:variables
}
